# items that will be deleted from player's inventories
banned-items:
  - 'barrier'
  - 'bedrock'
  - 'command_block'
  - 'repeating_command_block'
  - 'chain_command_block'
  - 'command_block_minecart'
  - 'end_portal_frame'
  - 'spawner'

# blocks that players will not be able to place
banned-blocks:
  - 'barrier'
  - 'bedrock'
  - 'end_portal_frame'
  - 'spawner'

# the delay (in ticks) between inventory scans
check-delay: 20